### ISSUE TITLE
Spanish translations

### ISSUE THREAD

**Issue by Nadai2010** [Darlington02/CairoLearnXinYminutes#1]
Hello, I must say that you do great work to teach in Starknet...I have the Min-Starknet repo and it is complete in Spanish with your guides and some of mine...If you want to review or add them it would be perfect for both communities. All the best

https://github.com/Nadai2010/Nadai-Aprender-Cairo-5-Minutos
https://github.com/Nadai2010/Nadai-Min-Starknet

**Comment by Darlington02** [comment]
Hello Nadia, thank you!

Great work you did with the min-starknet repo, could you add the Spanish translation in maybe a new folder and open a PR to the min-starknet repo here?

https://github.com/Darlington02/min-starknet

And the LearnXinYminutes will be completed soon...a translation to Spanish would also be very helpful too

**Comment by Darlington02** [comment]
Hello Nadia, thank you!

Great work you did with the min-starknet repo, could you add the Spanish translation in maybe a new folder and open a PR to the min-starknet repo here?

https://github.com/Darlington02/min-starknet

And the LearnXinYminutes will be completed soon...a translation to Spanish would also be very helpful too

**Comment by Nadai2010** [comment]
Hi Darlington, thanks for replying and the great job you did. I have created 2 files called `ES README`.

I will add the one for `min` and the one for `Yminutes`, but the latter can wait and I will add it with the translation when it is finished or when you need it, with great pleasure.
